Repository pscedu/singularity-gatk, pull requests merged in 2021-06, with the labels that each got.

#4 Added README file
  README.md
Labels: documentation

#5 Create LICENSE
  LICENSE
Labels: documentation

#7 Delete README.md
  4.1.9.0/README.md
Labels: bug, documentation

#11 Update README.md
  README.md
Labels: documentation

#12 Update README.md
  README.md
Labels: documentation

#13 Create test.sh
  4.1.9.0/test.sh
Labels: enhancement

#14 Create CONTRIBUTING.md
  4.1.9.0/Singularity
  CONTRIBUTING.md
Labels: documentation, enhancement

#17 Update Singularity
  4.1.9.0/Singularity
Labels: documentation, enhancement
